export default () => ({
    currentChannel: '',
    currentSearchText: '',
    articleChannels: {},
    latestArticles: [],
    recomendArticles: [],
    announcements: [],
    commissionRank:[],
    subItems: [],
    searchResults: [],
    newsSubItems: [],
    subItemPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    newsSubItemPagination:{
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    commentsPagination: {
        currentPageIndex: 1,
        hasNextPage: true,
        hasPreviousPage: true,
        pageSize: 20,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    articleComments: [],
    subItem: {},
    footerData: [],
    promotions: [],
    faqs:{shortdescription:""},
    faqsParams:{isCalculator:false}
})
