export default () => ({
    expertAuthData: {},
    expertData: {},
    roiTraders: [],
    tradersByProfitAndLoss: [],
    newTraders: [],
    allTraders: [],
    tags: [],
    selectedTrader: {},
    expertFollowers: [],
    selectedDuration: 7, // 7days, 30days,90days
    expertTrades: [],
    expertTradesHistory:[],
    followersUserTrade: [],
    followerUserTradeHistory: [],
    profitSharing: [],
    bestFollowers: [],
    bestExperts: {},

    allTraderPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    expertFollowersPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    followerUserTradePagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    followerUserTradeHistoryPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    profitSharingPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    myTradeHistoryPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    userProfitSharingPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    bestFollowersPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    expertTradesHistoryPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 0,
        totalPageCount: 1,
    },
    

    // User Center 
    myFollowerExperts: [],
    myFollowerData: {},
    myTrades: [],
    myTradeHistory: [],
    userProfitSharing: []
})
