export default () => ({
    games: [],
    selectedgame:{},
    selectedcurrency:'1533624980247416423',
    rooms: [],
    selectedroom:{},
    gameroominfo: {},
    blockHashes: [],
    players: [],
    openingbetting: [],
    historybetting: [],
    billingdetail:[],
    usergameassets: [],
    gamedata:{},
    usergamedata:{},
    betOrders: [],
    notifyResult:{},

    currentSelectedHash: {},
    hashGamesInfo: {},

    listPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    hashPagination: {
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 10,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    playerPagination:{
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 5,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    openPagination:{
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 3,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    historyPagination:{
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 5,
        totalItemCount: 9,
        totalPageCount: 1,
    },
    billingPagination:{
        currentPageIndex: 1,
        hasNextPage: false,
        hasPreviousPage: false,
        pageSize: 5,
        totalItemCount: 9,
        totalPageCount: 1,
    },


})
